[Configuration]

#Replace with your actual ChirpStack Tenant ID
tenant_id = your-tenant-id

#Replace with your actual ChirpStack application ID
app_id = your-app-id

#Replace with your ChirpStack server host address
server_host = 127.0.0.1

#Replace with your ChirpStack REST API URL
api_url = http://127.0.0.1:8090

#Replace with your ChirpStack MQTT port
mqtt_port = 1883

#Replace with your ChirpStack MQTT Username (Optional)
mqtt_username = 

#Replace with your ChirpStack MQTT Password (Optional)
mqtt_password = 

#Replace with your actual ChirpStack API Key
api_key = YOUR.API.KEY

#Replace with your device-specific root key (GenAppKey) in HEX
gen_app_key = 


[DEFAULT]
#list of devices eui (comma separated)
dev_eui_list = device-eui-00001, device-eui-00002 

#list of gateway id (comma separated)
gateway_id_list = gateway-id-00001, gateway-id-00002

#ChirpStack region enum, e.g. EU868, US915, CN470
region = CN470

#LoRaWAN data rate index for multicast transmissions; Lower DR (e.g., DR0 = SF12) gives better coverage (default is 0)
data_rate = 0

#LoRaWAN multicast Class C frequency (in Hz); must match device region and gateway support
frequency = 500300000

#Timeout for acknowledgement uplink message in seconds (default is 120)
ack_uplink_timeout = 120

#Wait after queuing AppTimeAns before sending McClassCSessionReq
clock_sync_downlink_grace_seconds = 10

#Session Timeout duration in seconds is 2^TimeOut (Example: TimeOut=8 means 256 seconds)
session_timeout_exponent = 8

#Set to false to retain multicast group on exit (default is true)
delete_mc_group_on_exit = true

#Set to true if network restricts outbound connection without proxy (default is false)
proxy_enabled = false

#Set complete proxy url e.g. http://username:password@proxy.example.com:8080 (default is blank)
proxy_url = 

#Set Corporate CA certificate path (absolute or relative) for TLS connection (default is blank)
corp_ca_cert_path = 

#Set to true to simulate the configurator without sending the request to ChirpStack (default is false)
dry_run = false

#logger level, possible values: debug, info, warning, error, critical (default is info)
logger_level = info
